# Generated by Django 5.0.6 on 2024-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_remove_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_saldo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
