# Generated by Django 5.0.4 on 2024-05-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='produto',
            new_name='item',
        ),
    ]
