# Generated by Django 5.0.4 on 2024-05-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_rename_produto_review_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_desp',
        ),
    ]
