# Generated by Django 5.0.4 on 2024-05-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_remove_review_review_desp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
